Add 2 blog posts from tbrisker devto blog
RedHat-Israel/RedHat-Israel.github.io pull request #53
Opened 2022-12-20 08:19 UTC by tbrisker

2022-12-20 08:36 UTC, TomerFi commented
I fixed the ci issue in the main branch.
a rebase should take care of the ci failure here.

2022-12-20 08:39 UTC, TomerFi commented
rebased - working on the next ci error.
this too is unrelated to this pr, but now that I see I can handle it.
this should be fast.

2022-12-20 10:28 UTC, TomerFi commented
@tbrisker sorry for taking your PR hostage, I wanted to fix our CI workflows to work for forks as well.
Now, we can see a preview of this PR, it looks like the images are not displayed:
https://redhat-israel.github.io/pr-previews/pr-53/posts/2022-06-19-attending-recruiting-fairs-as-an-engineer-b89/

2022-12-20 10:36 UTC, TomerFi commented
@bennypowers note that now - our ci (namely site previews) is working well for forks.
it's important to note though, the original single _pr_ workflow was splitted to accomplish this, we now have:
- [PR Build](https://github.com/RedHat-Israel/RedHat-Israel.github.io/blob/main/.github/workflows/pr_build.yml) build the site preview.
- [PR Deploy](https://github.com/RedHat-Israel/RedHat-Israel.github.io/blob/main/.github/workflows/pr_deploy.yml) deploys the site preview.
- [PR Teardown](https://github.com/RedHat-Israel/RedHat-Israel.github.io/blob/main/.github/workflows/pr_teardown.yml) deletes the site preview.

The later two will not report their status in PRs.

2022-12-20 15:02 UTC, bennypowers requested changes
Great stuff, @tbrisker 

Please make a few small but important changes, and we'll merge this

2022-12-20 15:02 UTC, bennypowers commented on posts/2022-06-19-attending-recruiting-fairs-as-an-engineer-b89.md
> +![Cover image](./assets/cover_image.jpeg)
Should have a descriptive alt text, instead of "cover image" which doesn't describe the contents of the image

2022-12-20 15:02 UTC, bennypowers commented on posts/2022-06-19-attending-recruiting-fairs-as-an-engineer-b89.md
> +![Image description](./assets/0qx6k0y7hgc3cgaitmze.jpg)
Alt text

2022-12-20 15:02 UTC, bennypowers commented on posts/2022-06-19-attending-recruiting-fairs-as-an-engineer-b89.md
> +![Image description](./assets/009po3nvjqn827hgu09a.jpg)
Alt text

2022-12-21 07:28 UTC, TomerFi commented
@tbrisker the jpg names are correct, but the pictures are still not visible in the preview site.
I think they should be moved to `/assets/img/` and referred accordingly.

@bennypowers can you confirm this?

2022-12-21 08:12 UTC, bennypowers commented
all urls (except fully-qualified) need to pass through `url` filter, because the DP's have a path prefix.

2022-12-21 08:23 UTC, bennypowers commented
- added `coverImage` and `coverImageAlt` frontmatter keys for post
- *don't worry about post styles* we'll cover that in a separate PR

2022-12-21 08:26 UTC, bennypowers approved these changes
Thanks Tomer!

2022-12-21 08:26 UTC, merged